### PR TITLE
7 little fixes by kballard, Nephyrin, and Buju

### PR DESCRIPTION
**Pull request by AlexFolland**
There have been some fixes by kballard, Nephyrin, and Buju.  I've been using my own fork for a while and it's probably worth going public with.

### CODE REVIEW

**Comment by brittyazel** [comment]
Some of these won't cleanly merge with my Master, and some aren't really necessary. Do you mind cleaning up this pull request a tiny bit, or maybe breaking it into specific commits?

**Comment by brittyazel** [comment]
What exactly is f65dbe4 doing?

**Comment by brittyazel** [comment]
Most of these actually appear to have been incorporated already. Perhaps SLO did this a while back.

Please rebase off of my build and tell me which of these still apply and need merging

**Comment by AlexFolland** [comment]
Oh, my mistake.  It looks like everything is actually incorporated already.  When I made the pull request, that appeared to not be true.  How odd.

There's still 1 InCombatLockdown() check in Ion_Bars.lua that isn't in your fork's master branch.  I had to add it a while ago because Ion was trying to run that section of code while in combat, which was not allowed.

I recommend just manually adding that one check in and closing this pull request.  Sorry for wasting your time with this confusing thing.  Thanks for looking into it.

**Comment by brittyazel** [comment]
Definitely not a waste of time! I highly appreciate you putting in pull requests :-)

I'm still learning what most of this code does, so its good for me to dig into it.

I will add that line.

Have you tried the currently released version 3.0.8 on your end to see if it is working for your needs? I noticed a LUA error when assigning a specific icon to a macro and you use the search box that I need to figure out.

**Comment by AlexFolland** [comment]
Yeah, I've been pulling your fixes into my repo.  There's been an issue with getting tooltips on mouseover sometimes, but that's all I've noticed.  I'll report it in a ticket here next time I see it.  I love that cursor icons while dragging works again.  I wish Ion-GUI was separate, so I didn't have to drag it out every time I git pull.  The reorganization otherwise has been very convenient though.

**Comment by brittyazel** [comment]
Do you have #showtooltip at the start of your macros?

I agree with the ion GUI, and I am actively trying to merge Ion and Ion-Gui into one. It's being tricky though, but I'll have it eventually

**Pull request closed without merging**
